
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 15 15:34:28 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 3;
  public static final int EQUALS = 18;
  public static final int POSTINC = 44;
  public static final int RIGHT_SQUARE_BRACKET = 12;
  public static final int NUMCONST = 50;
  public static final int CASE = 43;
  public static final int CONTINUE = 17;
  public static final int GREATER_THAN = 21;
  public static final int SEMICOLON = 5;
  public static final int RIGHT_CURLY_BRACE = 10;
  public static final int COMMA = 6;
  public static final int CLASS = 7;
  public static final int DIV = 27;
  public static final int RIGHT_PARENTHESIS = 14;
  public static final int QUESTION_MARK = 34;
  public static final int IF = 40;
  public static final int ASSIGN = 4;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int RETURN = 31;
  public static final int LOGICAL_OR = 30;
  public static final int LEFT_SQUARE_BRACKET = 11;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 26;
  public static final int ADD = 24;
  public static final int MOD = 28;
  public static final int IDENT = 47;
  public static final int BREAK = 16;
  public static final int VOID = 15;
  public static final int POSTDEC = 45;
  public static final int SWITCH = 42;
  public static final int COLON = 35;
  public static final int ELSE = 41;
  public static final int ENUM = 46;
  public static final int READ = 36;
  public static final int CHARCONST = 48;
  public static final int WHILE = 39;
  public static final int LESSER_THAN_OR_EQUAL_TO = 22;
  public static final int LOGICAL_AND = 29;
  public static final int NOT_EQUALS = 19;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 8;
  public static final int LEFT_CURLY_BRACE = 9;
  public static final int GREATER_THAN_OR_EQUAL_TO = 20;
  public static final int SUB = 25;
  public static final int DO = 38;
  public static final int PRINT = 37;
  public static final int LEFT_PARENTHESIS = 13;
  public static final int LESSER_THAN = 23;
}

